/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { SaveERC20 } from "./SaveERC20";
export type { Web3CXI } from "./Web3CXI";
