/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { SaveERC20__factory } from "./SaveERC20__factory";
export { Web3CXI__factory } from "./Web3CXI__factory";
