/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISaveERC20,
  ISaveERC20Interface,
} from "../../../contracts/interfaces/ISaveERC20";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISaveERC20__factory {
  static readonly abi = _abi;
  static createInterface(): ISaveERC20Interface {
    return new Interface(_abi) as ISaveERC20Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISaveERC20 {
    return new Contract(address, _abi, runner) as unknown as ISaveERC20;
  }
}
